# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Restore gradle.properties
      env:
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
        echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties
    - name: Restore release store file
      env:
        RELEASE_STORE_FILE: ${{ secrets.RELEASE_STORE_FILE }}
      shell: bash
      run: |
        echo ${RELEASE_STORE_BASE64} | base64 --decode > ~/.gradle/release_store.keyfile
    - name: Build with Gradle
      run: ./gradlew build
    - name: Generate Release APK
      run: ./gradlew assembleRelease --stacktrace
    - name: List Files
      run: find app/build
    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-debug-unsigned
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Upload Unsigned APK Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-release-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk
    - name: List Files
      run: find app/build
    - name: Upload Signed APK Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-debug-signed
        path: app/build/outputs/apk/release/app-release.apk
